[Test] setting environment to test functional code
YOCOING/YOCO pull request #20
Opened 2024-04-30 06:38 UTC by givvemee

Closes [issue link]

## Decsription

- Added one test code 
- Only validate copied valid file path in clipboard for now since there is one function at this point. `(./src/extension.ts)` 
- To run test, run `yarn run test:vscode` then check your clipboard by pasting command. 

## ETC

- 
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 테스트를 완료하였고, 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2024-04-30 13:29 UTC, fliklab commented on src/test/runTest.ts
> +    cp.spawnSync(cliPath, [...args, "--install-extension", "<EXTENSION-ID-OR-PATH-TO-VSIX>"], {
"<EXTENSION-ID-OR-PATH-TO-VSIX>" 부분이 vsix파일의 실제 경로가 들어가도록 수정해야 할 것 같습니다.

2024-04-30 13:34 UTC, fliklab commented on src/test/runTest.ts
> +    cp.spawnSync(cliPath, [...args, "--install-extension", "<EXTENSION-ID-OR-PATH-TO-VSIX>"], {
필요하다면 테스트가 돌아갈때 vsix파일을 특정경로에 자동으로 생성하게 만들면 어떨까 싶네요.

2024-05-02 00:35 UTC, givvemee commented on src/test/runTest.ts
> +    cp.spawnSync(cliPath, [...args, "--install-extension", "<EXTENSION-ID-OR-PATH-TO-VSIX>"], {
> `<EXTENSION-ID-OR-PATH-TO-VSIX>` 부분이 vsix파일의 실제 경로가 들어가도록 수정해야 할 것 같습니다.

Unique Identifier 로 수정 완이용 추가 제안 주신 사항은 고려해 보겠읍니다.

2024-05-02 11:48 UTC, fliklab commented on src/test/runTest.ts
> +    cp.spawnSync(cliPath, [...args, "--install-extension", "<EXTENSION-ID-OR-PATH-TO-VSIX>"], {
Unique Identifier 가 들어가면 출시되지 않은 기능에 대한 테스트가 안되기 때문에(마켓에서 익스텐션을 설치하게 되므로) vsix 파일 경로가 포함되는 방식으로 해야 할 것 같습니다.
완전 자동화는 당장 하지 않더라도 vsix 파일 생성은 수동으로 하고, 해당 파일을 통해서 테스트를 진행할 수 있도록 해야 할 것 같습니다.

2024-05-08 07:13 UTC, givvemee commented on src/test/runTest.ts
> +    cp.spawnSync(cliPath, [...args, "--install-extension", "<EXTENSION-ID-OR-PATH-TO-VSIX>"], {
@fliklab 다시 봐봐여

2024-05-09 06:00 UTC, fliklab requested changes

2024-05-09 06:00 UTC, fliklab commented on package.json
> +    "test:vscode": "yarn run compile && node ./out/test/runTest.js",
이 스크립트가 [ci.yml](https://github.com/YOCOING/YOCO/blob/dev/.github/workflows/ci.yml)에서 사용되고 있는데 PR에서 패키지 설치를 제대로 수행하지 못했는데도 불구하고 pass가 되는것 같습니다.

2024-05-09 06:06 UTC, fliklab commented
이 PR로 인한 테스트 변경사항이 CI에서 돌아가는 테스트에도 적용되는 것을 의도하신건지 궁금합니다. workflow에서도 적절한 테스트가 될 수 있도록 수정하거나, 혹은 다른 의도가 있다면(ex. 로컬에서 테스트 돌리는 용도?)  ci에서의 테스트와 분리 및 부연설명이 필요할 듯합니다.

2024-05-09 06:10 UTC, givvemee commented on package.json
> +    "test:vscode": "yarn run compile && node ./out/test/runTest.js",
아 그러네요 이거 테스트 다시 해볼게요

2024-05-09 06:12 UTC, givvemee commented
> 이 PR로 인한 테스트 변경사항이 CI에서 돌아가는 테스트에도 적용되는 것을 의도하신건지 궁금합니다. workflow에서도 적절한 테스트가 될 수 있도록 수정하거나, 혹은 다른 의도가 있다면(ex. 로컬에서 테스트 돌리는 용도?) ci에서의 테스트와 분리 및 부연설명이 필요할 듯합니다.

@fliklab 이 테스트 피알을 처음 올렸을 당시에는 로컬 테스트가 패스하는 것을 의도했고, ci 상에서는 로컬에서의 테스트의 결괏값을 가져갈 수 있도록 수정하면 좋을 것 같아요. 현재 이 피알에서는 로컬 테스트로만 한정합니다.

2024-05-09 06:24 UTC, fliklab commented
> > 이 PR로 인한 테스트 변경사항이 CI에서 돌아가는 테스트에도 적용되는 것을 의도하신건지 궁금합니다. workflow에서도 적절한 테스트가 될 수 있도록 수정하거나, 혹은 다른 의도가 있다면(ex. 로컬에서 테스트 돌리는 용도?) ci에서의 테스트와 분리 및 부연설명이 필요할 듯합니다.
> 
> @fliklab 이 테스트 피알을 처음 올렸을 당시에는 로컬 테스트가 패스하는 것을 의도했고, ci 상에서는 로컬에서의 테스트의 결괏값을 가져갈 수 있도록 수정하면 좋을 것 같아요. 현재 이 피알에서는 로컬 테스트로만 한정합니다.

@givvemee ci에서 로컬 테스트의 결과값을 가져간다는게 잘 이해가 안됩니다. 

일단 제가 이해한대로 생각해보면, 이 PR이 CI에 영향이 없으려면 `./out/test/runTest.js`를 하려면 workflow에서 vsix파일을 생성하는 스크립트를 실행을 하거나, 아니면 headless로 실행하는 기존 "vscode-test"를 사용하는 방식대로 해야 하는거 아닐까 싶은데요.  

정확한 이해가 아니라서 틀릴 수도 있는 점 이해 부탁드립니다.

2024-05-09 06:34 UTC, givvemee commented
> > > 이 PR로 인한 테스트 변경사항이 CI에서 돌아가는 테스트에도 적용되는 것을 의도하신건지 궁금합니다. workflow에서도 적절한 테스트가 될 수 있도록 수정하거나, 혹은 다른 의도가 있다면(ex. 로컬에서 테스트 돌리는 용도?) ci에서의 테스트와 분리 및 부연설명이 필요할 듯합니다.
> > 
> > 
> > @fliklab 이 테스트 피알을 처음 올렸을 당시에는 로컬 테스트가 패스하는 것을 의도했고, ci 상에서는 로컬에서의 테스트의 결괏값을 가져갈 수 있도록 수정하면 좋을 것 같아요. 현재 이 피알에서는 로컬 테스트로만 한정합니다.
> 
> @givvemee ci에서 로컬 테스트의 결과값을 가져간다는게 잘 이해가 안됩니다.
> 
> 일단 제가 이해한대로 생각해보면, CI에서 `./out/test/runTest.js`를 하려면 ci workflow에서 vsix파일을 생성하는 스크립트를 실행을 하거나, 아니면 이 PR이 CI에 영향이 없으려면 headless로 실행하는 기존 "vscode-test"를 사용하는 방식대로 해야 하는거 아닐까 싶은데요.
> 
> 정확한 이해가 아니라서 틀릴 수도 있는 점 이해 부탁드립니다.

@fliklab 
이 PR 에서 테스트하는 건 로컬에서 작성된 (성훈 님이 만드신 기본 기능) extension 기능을 테스트한다고 가정을 하고, 앞으로 생길 기능들에 대해서는 테스트하지 않습니다. 그래서 처음에 VSIX 파일을 보는 게 아니라 Unique Identifier 를 작성했고요.... `vscode-test` 돌리면 이 테스트 기능은 여기서 종료해도 되는데, 헤드리스 기반에서 출시되지 않은 기능까지 테스트 하는 것을 의식의 흐름대로 이 피알에 포함을 하려다 보니 좀 꼬인 면이 있는 것 같아요. 일단 vscode-test 로 픽스해서 올리는 게 좋아 보입니다.

2024-05-09 06:37 UTC, givvemee commented
@fliklab `ci에서 로컬 테스트의 결과값을 가져간다는게 잘 이해가 안됩니다.` 이거는 테스트 플로우와 다른 소리가 되어버렸습니다! 무시해 주세여.

2024-05-09 06:44 UTC, givvemee commented
@fliklab 다시 봐봐여

2024-05-09 07:13 UTC, fliklab commented on package.json
>      "pretest": "yarn run compile && yarn run lint && mv *.vsix src/test/",
`&& mv *.vsix src/test/`도 빠져야 하는거 아닐까요?

2024-05-09 07:13 UTC, givvemee commented on package.json
>      "pretest": "yarn run compile && yarn run lint && mv *.vsix src/test/",
악!!!!!!!!!!! 맞다.

2024-05-09 07:14 UTC, fliklab reviewed
이미 릴리즈 된것을 테스트 하는게 좀 의문이긴 합니다만 일단 TODO로 남기신 부분 확인은 했고 추후 이부분의 정리가 필요는 할 듯 합니다..!

2024-05-09 07:16 UTC, fliklab commented
새로 생긴 runTest 파일에 대한 정체성을 명확히 하기 위해서 package.json에 `test:local`처럼 스크립트 하나 추가해도 괜찮을 것 같습니다.

2024-05-09 07:17 UTC, givvemee commented
> 이미 릴리즈 된것을 테스트 하는게 좀 의문이긴 합니다만 일단 TODO로 남기신 부분 확인은 했고 추후 이부분의 정리가 필요는 할 듯 합니다..!

이거는 저희가 이 이슈를 한 달 전에 올려서 기억이 퇴색된 것일 수 있지만, 기능 개발 / 기능 테스트 코드 / CI 로 첫 배포 전 업무 분배하기로 한 것이 바로 머지가 안 됐어여. 이 PR 이 길어지면서 이것저것 아이디어가 많이 나와서 그걸 조합하려다 보니 그렇게 됐네요.

2024-05-09 07:20 UTC, givvemee commented
> 새로 생긴 runTest 파일에 대한 정체성을 명확히 하기 위해서 package.json에 `test:local`처럼 스크립트 하나 추가하면 좋을 것 같습니다.

@fliklab 코드를 읽어보면 `src/utils/index.ts` 내부에서 정의되는 테스트들을 yoco.YOCO (unique identifier) 확장 프로그램을 설치하여 통합 테스트 하는 환경을 구축하는 것으로 이해할 수 있다고 판단되어서 별도 스크립트 추가하지 않습니다. 필요하다면 추후 주석을 추가하는 쪽이 좋을 것 같아요.

2024-05-09 07:36 UTC, fliklab commented
> > 새로 생긴 runTest 파일에 대한 정체성을 명확히 하기 위해서 package.json에 `test:local`처럼 스크립트 하나 추가하면 좋을 것 같습니다.
> 
> @fliklab 코드를 읽어보면 `src/utils/index.ts` 내부에서 정의되는 테스트들을 yoco.YOCO (unique identifier) 확장 프로그램을 설치하여 통합 테스트 하는 환경을 구축하는 것으로 이해할 수 있다고 판단되어서 별도 스크립트 추가하지 않습니다. 필요하다면 추후 주석을 추가하는 쪽이 좋을 것 같아요.

추후 정리하는걸로 생각하고 다음 단계로 가기 위해 Approve하겠습니다.

2024-05-09 07:37 UTC, fliklab approved these changes

2024-05-09 07:40 UTC, merged